const genders = [
    {
        "word": "a",
        "index": "0",
        "default": "0",
        "qtd_itens": "72",
        "exceptions": [
            "bliw",
            "br",
            "civ",
            "clim",
            "diem",
            "dnar",
            "du",
            "err",
            "fa",
            "h|",
            "hc",
            "ho",
            "hpa",
            "htan",
            "ile|",
            "iledr",
            "imer",
            "ja",
            "jr",
            "ka",
            "kk",
            "la|",
            "lg",
            "lit",
            "liv",
            "loc",
            "lro",
            "man",
            "may",
            "mini",
            "mlaj",
            "mn",
            "mru",
            "muz",
            "ng",
            "nnat",
            "np",
            "om",
            "raj",
            "rat",
            "raug",
            "rieb",
            "riev",
            "rik",
            "riu",
            "rp",
            "ruj",
            "rum",
            "rut",
            "sa",
            "ssa",
            "ssu",
            "tai|",
            "tano",
            "tari",
            "tel",
            "terp",
            "toj",
            "tsi",
            "ua",
            "ud",
            "uh",
            "uq",
            "va",
            "vd",
            "vi|",
            "vlis",
            "vo",
            "vr",
            "w",
            "yan",
            "zuo"
        ]
    },
    {
        "word": "b",
        "index": "1",
        "default": "1",
        "qtd_itens": "1",
        "exceptions": [
            "adani"
        ]
    },
    {
        "word": "c",
        "index": "2",
        "default": "1",
        "qtd_itens": "2",
        "exceptions": [
            "il",
            "it"
        ]
    },
    {
        "word": "d",
        "index": "3",
        "default": "1",
        "qtd_itens": "2",
        "exceptions": [
            "ade",
            "ir"
        ]
    },
    {
        "word": "e",
        "index": "4",
        "default": "0",
        "qtd_itens": "168",
        "exceptions": [
            "ad",
            "aj",
            "ak",
            "bao",
            "bu",
            "cal",
            "ced",
            "cilef",
            "ciru",
            "cn",
            "curb",
            "dad",
            "deb",
            "di|",
            "dia|",
            "diat",
            "dic",
            "dila",
            "div",
            "dla",
            "dlih",
            "dlinesa",
            "dn",
            "do",
            "el",
            "g|",
            "ge",
            "go",
            "gr",
            "gu",
            "hp",
            "ib",
            "ile",
            "ill",
            "in",
            "j",
            "ke",
            "ki",
            "klo",
            "kn",
            "ko",
            "ks",
            "ku",
            "lat",
            "lau",
            "lav",
            "lc",
            "ledr",
            "leg",
            "leit",
            "len",
            "less",
            "leu",
            "lh",
            "libat",
            "lil",
            "lir",
            "lled",
            "lo",
            "ly",
            "ma",
            "mea",
            "med",
            "mi",
            "ml",
            "mr",
            "ms",
            "mu",
            "my",
            "nahp",
            "nan",
            "navi",
            "navla",
            "navle",
            "navlig",
            "navo",
            "ned",
            "neico",
            "neit",
            "nelig",
            "nelsu",
            "ner|",
            "niav",
            "niaw",
            "nidla",
            "nidu",
            "nim",
            "nin",
            "nio",
            "nitr",
            "nnav",
            "nner",
            "nnh",
            "nnoi",
            "noc",
            "nod",
            "noe",
            "nof",
            "noice",
            "noicla",
            "noide",
            "noih",
            "noj",
            "nor",
            "not",
            "nr",
            "nu",
            "oi",
            "on",
            "pe",
            "pi",
            "po",
            "pp",
            "py",
            "ras",
            "rb",
            "rd",
            "reb",
            "red",
            "rf",
            "ria",
            "rih",
            "ro",
            "rr",
            "rt",
            "sd",
            "se",
            "sieg",
            "sliw",
            "soj",
            "sr",
            "sse",
            "ssu",
            "su",
            "tea",
            "tedlaw",
            "tedoi",
            "teds",
            "teia",
            "tesin",
            "teze",
            "tezin",
            "tided",
            "tiu",
            "tl",
            "tna",
            "tne",
            "tra",
            "treal",
            "treh",
            "trei",
            "tser",
            "ua",
            "ug",
            "uo",
            "uqa",
            "uqe",
            "uqia",
            "uqini",
            "uqir",
            "uql",
            "uqo",
            "uqr",
            "use",
            "uso",
            "uzo",
            "vat",
            "vi"
        ]
    },
    {
        "word": "f",
        "index": "5",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "g",
        "index": "6",
        "default": "1",
        "qtd_itens": "5",
        "exceptions": [
            "ie",
            "neh",
            "nipm",
            "nob",
            "nuj"
        ]
    },
    {
        "word": "h",
        "index": "7",
        "default": "1",
        "qtd_itens": "12",
        "exceptions": [
            "ak",
            "an",
            "ar",
            "s",
            "teb",
            "ter",
            "tes",
            "tezil",
            "tezir",
            "tide|",
            "tidu",
            "tur"
        ]
    },
    {
        "word": "i",
        "index": "8",
        "default": "1",
        "qtd_itens": "96",
        "exceptions": [
            "ale",
            "ana",
            "ano",
            "ba",
            "cajd",
            "calg",
            "caram",
            "cari|",
            "carid",
            "carol",
            "cedli",
            "cen|",
            "cia",
            "cira",
            "cle|",
            "cn",
            "co",
            "cu",
            "dak",
            "diel",
            "dir",
            "duh",
            "elrih",
            "elris",
            "em|",
            "enir",
            "ha",
            "j|",
            "ki",
            "kusi",
            "kuy|",
            "lag",
            "lar",
            "legn",
            "lei",
            "lek",
            "lel",
            "len",
            "les",
            "leu",
            "lev",
            "lez",
            "li",
            "lleh",
            "llek",
            "lra",
            "lrednaw",
            "mah",
            "mei",
            "meo",
            "mor",
            "mt",
            "muss",
            "muy",
            "muz",
            "nab",
            "nai",
            "nari",
            "nas",
            "nat",
            "naul",
            "nav|",
            "navi|",
            "navli",
            "nay",
            "ne|",
            "nec",
            "neg",
            "nel",
            "neru",
            "neso|",
            "nev",
            "nez",
            "nic",
            "nie",
            "nil",
            "nnej",
            "nom",
            "nu",
            "ram",
            "rev",
            "rh",
            "roa",
            "ruya",
            "sl",
            "sr",
            "sseg",
            "tor",
            "ts",
            "tter",
            "tteu",
            "ua",
            "vai",
            "z|",
            "zaz",
            "zus"
        ]
    },
    {
        "word": "j",
        "index": "9",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "k",
        "index": "10",
        "default": "1",
        "qtd_itens": "2",
        "exceptions": [
            "an",
            "l"
        ]
    },
    {
        "word": "l",
        "index": "11",
        "default": "1",
        "qtd_itens": "13",
        "exceptions": [
            "am",
            "eb|",
            "ebam",
            "ebar",
            "ebas",
            "ebaz",
            "ehca",
            "eht",
            "euq",
            "iag",
            "inel",
            "lem",
            "o"
        ]
    },
    {
        "word": "m",
        "index": "12",
        "default": "1",
        "qtd_itens": "8",
        "exceptions": [
            "ailil",
            "air",
            "aiv",
            "arim",
            "ee",
            "eleu",
            "em",
            "er"
        ]
    },
    {
        "word": "n",
        "index": "13",
        "default": "1",
        "qtd_itens": "33",
        "exceptions": [
            "ailil",
            "aillil",
            "airam",
            "airi",
            "airy",
            "aivi",
            "ale",
            "alir",
            "asu",
            "avin",
            "avira",
            "ayri",
            "azu",
            "eho",
            "ekc",
            "ele",
            "ell",
            "em",
            "era",
            "ets",
            "ielr",
            "ilek",
            "ilev",
            "ims",
            "ir",
            "itsi",
            "itsr",
            "na|",
            "ny",
            "orah",
            "uk",
            "us",
            "y"
        ]
    },
    {
        "word": "o",
        "index": "14",
        "default": "1",
        "qtd_itens": "30",
        "exceptions": [
            "acie",
            "ce",
            "cim",
            "cit",
            "d|",
            "h|",
            "ico",
            "ka",
            "ke",
            "kiek",
            "kies",
            "kihc",
            "kihs",
            "kika",
            "kiku",
            "kim",
            "kir",
            "kit",
            "ko",
            "kur",
            "kus",
            "kuy",
            "kuzi",
            "leu",
            "nats",
            "niruam",
            "rro",
            "tej",
            "tnem",
            "ul"
        ]
    },
    {
        "word": "p",
        "index": "15",
        "default": "1",
        "qtd_itens": "1",
        "exceptions": [
            "iy"
        ]
    },
    {
        "word": "q",
        "index": "16",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "r",
        "index": "17",
        "default": "1",
        "qtd_itens": "33",
        "exceptions": [
            "al",
            "amal",
            "amaz",
            "amicy",
            "amidi",
            "amidue",
            "amilo",
            "amisl",
            "amizl",
            "amsire",
            "anide",
            "effi",
            "efi",
            "ehta",
            "ehts",
            "epse",
            "etse|",
            "iadam",
            "ialce",
            "ialo",
            "ian|",
            "icalg",
            "idan|",
            "idel",
            "inav|",
            "inave|",
            "inec|",
            "inele",
            "inez",
            "inoi",
            "oif",
            "onoe",
            "ycar"
        ]
    },
    {
        "word": "s",
        "index": "18",
        "default": "1",
        "qtd_itens": "51",
        "exceptions": [
            "adinu",
            "aitak",
            "ecr",
            "edec",
            "edio",
            "edlia",
            "edred",
            "edru",
            "eduel",
            "edui",
            "egri",
            "ekl",
            "eleg",
            "enele",
            "eng",
            "eni|",
            "enia",
            "enid|",
            "enir",
            "ep",
            "ered",
            "erim|",
            "erima",
            "ero",
            "even",
            "iah",
            "ial",
            "iat",
            "ida",
            "ila",
            "ile|",
            "ili",
            "ill",
            "ily",
            "inedl",
            "inna",
            "io",
            "ira",
            "irc|",
            "iri|",
            "irim",
            "iris",
            "irod",
            "iry",
            "isi",
            "itr",
            "iz",
            "orieh",
            "yd",
            "yni",
            "yr"
        ]
    },
    {
        "word": "t",
        "index": "19",
        "default": "1",
        "qtd_itens": "7",
        "exceptions": [
            "eb",
            "er",
            "ide|",
            "ig",
            "se",
            "ten",
            "ti"
        ]
    },
    {
        "word": "u",
        "index": "20",
        "default": "1",
        "qtd_itens": "4",
        "exceptions": [
            "d|",
            "la",
            "rahim|",
            "s|"
        ]
    },
    {
        "word": "v",
        "index": "21",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "w",
        "index": "22",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "x",
        "index": "23",
        "default": "1",
        "qtd_itens": "0",
        "exceptions": []
    },
    {
        "word": "y",
        "index": "24",
        "default": "1",
        "qtd_itens": "55",
        "exceptions": [
            "am",
            "ana",
            "anoi",
            "cal",
            "cara|",
            "cari|",
            "carod",
            "cav",
            "cira",
            "clao",
            "cn",
            "cren",
            "cu",
            "dal",
            "deh",
            "elrih",
            "enar",
            "g",
            "ha",
            "htor",
            "lat",
            "lea",
            "lecu",
            "leg",
            "lek",
            "len",
            "les",
            "leu",
            "lev",
            "lez",
            "lia",
            "lir",
            "lle",
            "lram",
            "mat",
            "nai",
            "nari",
            "nas",
            "nau",
            "navl",
            "naw",
            "neg",
            "nel",
            "neu",
            "nna",
            "nom",
            "ram",
            "remi",
            "rems",
            "ri",
            "ror",
            "si",
            "so",
            "su",
            "t"
        ]
    },
    {
        "word": "z",
        "index": "25",
        "default": "1",
        "qtd_itens": "6",
        "exceptions": [
            "eni|",
            "enir",
            "ered",
            "il",
            "ir",
            "u"
        ]
    }
];

module.exports = genders;